# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 04:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=40)),
                ('capacity', models.IntegerField()),
                ('floor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('exam', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sap_id',
            field=models.BigIntegerField(default=60004150109, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(10000000000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='sap_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(10000000000)]),
        ),
        migrations.AddField(
            model_name='teacher_allotment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
        migrations.AddField(
            model_name='student_allotment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student_Detail'),
        ),
    ]
