# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180128_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
    ]
